### PR TITLE
Feature/create_read_delete

### PR DESCRIPTION
**Pull request by uly3**

### CODE REVIEW

**Comment by wtvamp** [comment]
Well, hot damn Team 3 - you are off to a great start.  Don't forget to have your peers write some code as well.

**Comment by uly3** [comment]
> Well, hot damn Team 3 - you are off to a great start. Don't forget to have your peers write some code as well.

Yup.
I still need to do a couple of things: 

-I still need to figure out how to do the Read part of the CRUD with the JpaRepository stuff. 
-Not sure how to go about testing if stuff works but I still need to test stuff out. lol

**Comment by brettyates** [comment]
Take a look at my commit...hopefully that will get you started. The error with "Optional" was because java.util.Optional wasn't being imported. I can spend some more time with it later today if you're still having trouble.

**Comment by uly3** [comment]
Thanks. I’ll look into it.

**Comment by uly3** [comment]
NPC edits

Not sure how to test stuff exacty, I don't know if creating a html file for each remaing crud task is the way  to test READ,DELETE,and UPDATE. I think the RepoDataHandler methods are good, not sure about the controller though.

**Pull request merged**
